FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim

WORKDIR /app

ENV UV_CACHE_DIR=/root/.cache/uv
ENV UV_HTTP_TIMEOUT=120

COPY requirements-frontend.txt /app/requirements-frontend.txt
RUN --mount=type=cache,target=/root/.cache/uv uv pip install --system -v -r /app/requirements-frontend.txt

COPY app.py /app/app.py

EXPOSE 8501
CMD ["python", "-m", "streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
